name: Deploy to hiverift.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Deploy
        run: |
          curl -s \
            -H "Authorization: cpanel hiveriftmain:${{ secrets.CPANEL_API_TOKEN }}" \
            "https://69.170.178.68:2083/execute/Script/run?script=%2Fhome%2Fhiveriftmain%2Fdeploy.sh"